language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install --frozen-lockfile
script:
  - yarn lint
  - yarn test --coverage
after_success:
  - 'coveralls < coverage/lcov.info'
